<?php $shopId=addslashes(Mage::getStoreConfig('cocote/catalog/shop_id')); ?>
<?php $order=Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId()); ?>

<?php if($shopId): ?>
<script src="https://js.cocote.com/script-confirm-fr.min.js"></script>
  <script type="text/javascript">
    new CocoteTSC({
      lang: "fr",
      mSiteId: "<?php echo $shopId; ?>",
      amount: <?php echo $order->getGrandTotal(); ?>,
      orderId: <?php echo $order->getIncrementId(); ?>
    });
    
  </script>
<?php endif; ?>